"""
escalation_handler — Lambda entry point
Handles two operations detected by event shape:

Operation A — Called by Step Functions (EscalateForApproval state, .waitForTaskToken):
  - Store task_token in DynamoDB against case_id
  - Publish SNS alert with approve/reject URLs
  - Return immediately (Step Functions pauses waiting for task token callback)

Operation B — Called by API Gateway POST /approve or POST /reject:
  - Validate task_token from DynamoDB
  - Call sfn.send_task_success or send_task_failure
  - Update DynamoDB approval_status
  - Write audit_trail entry
"""

import json
import os
import urllib.parse
import boto3
from datetime import datetime, timezone
from botocore.exceptions import ClientError

# ── AWS clients ───────────────────────────────────────────────────────────────
dynamodb = boto3.resource("dynamodb")
sns = boto3.client("sns")
sfn = boto3.client("stepfunctions")
cloudwatch = boto3.client("cloudwatch")

# ── Environment variables ─────────────────────────────────────────────────────
TABLE_NAME = os.environ["TABLE_NAME"]
SNS_TOPIC_ARN = os.environ["SNS_TOPIC_ARN"]
API_GATEWAY_URL = os.environ["API_GATEWAY_URL"]


def _write_audit(table, case_id: str, created_at: str, action: str, detail: dict):
    now = datetime.now(timezone.utc).isoformat()
    table.update_item(
        Key={"case_id": case_id, "created_at": created_at},
        UpdateExpression="SET audit_trail = list_append(if_not_exists(audit_trail, :empty), :entry)",
        ExpressionAttributeValues={
            ":empty": [],
            ":entry": [{"action": action, "timestamp": now, "detail": json.dumps(detail)}],
        },
    )


def _operation_a(event: dict, table) -> dict:
    """Step Functions invocation — store token, send SNS."""
    case_id = event["case_id"]
    created_at = event["created_at"]
    task_token = event["task_token"]  # injected by Step Functions .waitForTaskToken
    risk_level = event.get("risk_level", "UNKNOWN")
    deadline = event.get("deadline", "Not specified")
    required_action = event.get("required_action", "Review required")

    # Fetch draft preview from DynamoDB
    resp = table.get_item(Key={"case_id": case_id, "created_at": created_at})
    item = resp.get("Item", {})
    draft = item.get("draft_response", "No draft available")
    draft_preview = " ".join(draft.split()[:150])  # first 150 words

    # Store task_token in DynamoDB
    table.update_item(
        Key={"case_id": case_id, "created_at": created_at},
        UpdateExpression="SET task_token = :tt, approval_status = :st",
        ExpressionAttributeValues={
            ":tt": task_token,
            ":st": "AWAITING_APPROVAL",
        },
    )

    # Build approve/reject URLs
    encoded_token = urllib.parse.quote(task_token, safe="")
    approve_url = f"{API_GATEWAY_URL}/approve?token={encoded_token}&case_id={case_id}"
    reject_url = f"{API_GATEWAY_URL}/reject?token={encoded_token}&case_id={case_id}"

    # Publish SNS
    subject = f"[URGENT] CivicGuardian — Case {case_id[:8]} requires your approval"
    body = f"""Risk Level: {risk_level}
Deadline: {deadline}
Summary: {required_action}

Draft preview:
{draft_preview}

To APPROVE: {approve_url}

To REJECT: {reject_url}

Case ID: {case_id}
This message was generated by CivicGuardian AI. The draft is for review only — not legal advice."""

    sns.publish(
        TopicArn=SNS_TOPIC_ARN,
        Subject=subject,
        Message=body,
    )

    # Audit trail
    _write_audit(table, case_id, created_at, "ESCALATED_FOR_APPROVAL", {
        "risk_level": risk_level,
        "deadline": deadline,
        "approve_url": approve_url,
        "reject_url": reject_url,
    })

    print(json.dumps({"case_id": case_id, "event": "escalated", "risk_level": risk_level}))
    return {"statusCode": 200, "body": json.dumps({"case_id": case_id, "status": "AWAITING_APPROVAL"})}


def _operation_b(event: dict, table) -> dict:
    """API Gateway invocation — process approve or reject."""
    http_method = event.get("httpMethod", "")
    path = event.get("path", "")

    # Support both query string and body
    params = event.get("queryStringParameters") or {}
    body_raw = event.get("body") or "{}"
    try:
        body = json.loads(body_raw)
    except Exception:
        body = {}

    case_id = params.get("case_id") or body.get("case_id")
    encoded_token = params.get("token") or body.get("task_token")

    if not case_id or not encoded_token:
        return {"statusCode": 400, "body": json.dumps({"error": "Missing case_id or token"})}

    task_token = urllib.parse.unquote(encoded_token)

    # Fetch created_at and stored token from DynamoDB (query by case_id)
    # We need created_at for the key — fetch via scan with filter (acceptable for low volume)
    ddb_client = boto3.client("dynamodb")
    scan_resp = ddb_client.query(
        TableName=TABLE_NAME,
        KeyConditionExpression="case_id = :cid",
        ExpressionAttributeValues={":cid": {"S": case_id}},
        Limit=1,
    )
    items = scan_resp.get("Items", [])
    if not items:
        return {"statusCode": 404, "body": json.dumps({"error": "Case not found"})}

    created_at = items[0]["created_at"]["S"]
    stored_token = items[0].get("task_token", {}).get("S", "")

    if stored_token != task_token:
        return {"statusCode": 403, "body": json.dumps({"error": "Invalid task token"})}

    caseworker_id = body.get("caseworker_id", params.get("caseworker_id", "unknown"))
    now = datetime.now(timezone.utc).isoformat()

    if "/approve" in path or http_method == "POST" and "approve" in path:
        sfn.send_task_success(
            taskToken=task_token,
            output=json.dumps({"approved": True, "caseworker_id": caseworker_id, "approved_at": now}),
        )
        table.update_item(
            Key={"case_id": case_id, "created_at": created_at},
            UpdateExpression="SET approval_status = :st, caseworker_id = :cw, approved_at = :at",
            ExpressionAttributeValues={
                ":st": "APPROVED",
                ":cw": caseworker_id,
                ":at": now,
            },
        )
        _write_audit(table, case_id, created_at, "APPROVED_BY_CASEWORKER", {
            "caseworker_id": caseworker_id,
            "approved_at": now,
        })
        print(json.dumps({"case_id": case_id, "event": "approved", "caseworker_id": caseworker_id}))
        return {"statusCode": 200, "body": json.dumps({"case_id": case_id, "status": "APPROVED"})}

    elif "/reject" in path:
        rejection_reason = body.get("rejection_reason", params.get("rejection_reason", "No reason provided"))
        sfn.send_task_failure(
            taskToken=task_token,
            error="CaseworkerRejected",
            cause=rejection_reason,
        )
        table.update_item(
            Key={"case_id": case_id, "created_at": created_at},
            UpdateExpression="SET approval_status = :st, rejection_reason = :rr",
            ExpressionAttributeValues={
                ":st": "REJECTED",
                ":rr": rejection_reason,
            },
        )
        _write_audit(table, case_id, created_at, "REJECTED_BY_CASEWORKER", {
            "caseworker_id": caseworker_id,
            "rejection_reason": rejection_reason,
        })
        print(json.dumps({"case_id": case_id, "event": "rejected"}))
        return {"statusCode": 200, "body": json.dumps({"case_id": case_id, "status": "REJECTED"})}

    return {"statusCode": 400, "body": json.dumps({"error": "Unknown operation"})}


def lambda_handler(event, context):
    table = dynamodb.Table(TABLE_NAME)

    # Detect operation by event shape
    if "task_token" in event and "httpMethod" not in event:
        return _operation_a(event, table)
    elif "httpMethod" in event or "requestContext" in event:
        return _operation_b(event, table)
    else:
        return {"statusCode": 400, "body": json.dumps({"error": "Unrecognised event shape"})}
